networks:
  backend:

services:
  customerdb:
    container_name: customer-db
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
        - ACCEPT_EULA=Y
        - SA_PASSWORD=P@ssword
    networks:
        - backend
    ports:
        - 8001:1433

  customerwebapi:
    container_name: customer-api
    image: ${DOCKER_REGISTRY-}customerwebapi
    build:
      context: .
      dockerfile: CustomerWebApi/Dockerfile
    networks:
        - backend
    ports:
        - 8002:8080
    environment:
        - DB_HOST=customerdb
        - DB_NAME=dms_customer
        - DB_SA_PASSWORD=P@ssword 

  productdb:
    container_name: product-db
    image: mysql:9.0.1-oracle
    environment: 
        - MYSQL_ROOT_PASSWORD=P@ssword
    networks:
        - backend
    ports:
        - 8003:3306

  productwebapi:
    container_name: product-api
    image: ${DOCKER_REGISTRY-}productwebapi
    build:
      context: .
      dockerfile: ProductWebApi/Dockerfile
    networks:
        - backend
    ports:
        - 8004:8080
    environment:
        - DB_HOST=productdb
        - DB_NAME=dms_product
        - DB_ROOT_PASSWORD=P@ssword

  orderdb:
    container_name: order-db
    image: mongo
    networks:
        - backend
    ports:
        - 8005:27017

  orderwebapi:
    container_name: order-api
    image: ${DOCKER_REGISTRY-}orderwebapi
    build:
      context: .
      dockerfile: OrderWebApi/Dockerfile
    ports:
        - 8006:8080
    networks:
        - backend
    environment:
        - DB_HOST=orderdb
        - DB_NAME=dms_order
